services:
  client:
    container_name: habit_dev_client
    build: ./client
    image: habit_client
    ports:
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: ["http-server"]
